In [1]:
x=2
x1=3
x*x1

6

### Loops and Decision

In [4]:
# for loop is used when the statement is true to repeat execution
names = ['chizoba', 'amanda', 'zara', 'uche', 'charles']
for i in names:
    print(f'{i}, nice to meet you')

chizoba, nice to meet you
amanda, nice to meet you
zara, nice to meet you
uche, nice to meet you
charles, nice to meet you


In [15]:
# while loop is used over a sequence for iteration
price = 10
while price < 10:
    price1 = price * 0.2
print('new price')

new price


In [5]:
sales = [20, 40, 15, 10, 5, 2]

In [30]:
for i in sales:
    if i >= 20:
        print(f'high sale')

    elif i >= 10:
        print('low sale')

    elif i == 5:
        print('very low sale')

    else:
        print('poor sale')

high sale
high sale
low sale
low sale
very low sale
poor sale


### Error handling

In [46]:
# try and except statement is used when error is anticipated

try:
    if score == hello:
        print(yes)

except:
    print('wrong format')

wrong format


In [59]:
 x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
try:
    x1 = x.str
    print('true')

except:
    print('false')

false


In [61]:
try:
    range(10)
    print(range(10)/0)

except:
    print('invalid input')

invalid input


### Functions in python

In [15]:
#defining a function to add the number of sales
def add_nums(sales, sales1):
    return sales + sales1
print(add_nums(sales, sales1))

[20, 40, 15, 10, 5, 2, 5, 10, 15, 20, 25, 30]


In [57]:
def greeting(names):
    return 'Welcome,'+ ' ' + names

print (greeting('chizoba'))
print(greeting('uche'))

Welcome, chizoba
Welcome, uche


In [62]:
sales1 = [5, 10, 15, 20, 25, 30]

### File handling and data output/input

In [2]:
#Getting our file
# First we import our libraries

import numpy as np
import pandas as pd

# to read our csv file

x = pd.read_csv('Book11.csv')
x

orderid  order no   name  qty  amount
0     1001         1    pat   15      50
1     1002         2  chris    4      10
2     1003         3   wema   25      85
3     1004         4  buchy   32     105
4     1005         5  sanda   12      35
5     1006         6   lund    6       8
6     1007         7   kels    9      42
7     1008         8   dona   27      92

In [78]:
x.describe()

orderid  order no        qty      amount
count     8.00000   8.00000   8.000000    8.000000
mean   1004.50000   4.50000  16.250000   53.375000
std       2.44949   2.44949  10.471049   36.986243
min    1001.00000   1.00000   4.000000    8.000000
25%    1002.75000   2.75000   8.250000   28.750000
50%    1004.50000   4.50000  13.500000   46.000000
75%    1006.25000   6.25000  25.500000   86.750000
max    1008.00000   8.00000  32.000000  105.000000

In [79]:
x.info

<bound method DataFrame.info of    orderid  order no   name  qty  amount
0     1001         1    pat   15      50
1     1002         2  chris    4      10
2     1003         3   wema   25      85
3     1004         4  buchy   32     105
4     1005         5  sanda   12      35
5     1006         6   lund    6       8
6     1007         7   kels    9      42
7     1008         8   dona   27      92>

In [ ]:
x.to_save('httdatachallenge')

### Numpy operations

In [1]:
import numpy as np

In [3]:
nums = [2, 4, 6, 8, 10, 12]
num = [1, 3, 5, 7, 9, 11]

In [4]:
# creating arrays
np.array(nums)

array([ 2,  4,  6,  8, 10, 12])

In [7]:
np.array(num)

array([ 1,  3,  5,  7,  9, 11])

In [9]:
# basic arithmetic operations
nar = np.array(nums) + np.array(num)
print(nar)

[ 3  7 11 15 19 23]


In [11]:
nar2 = np.array(nums) - np.array(num)
nar2

array([1, 1, 1, 1, 1, 1])

In [13]:
nar3 = np.array(nums) * np.array(num)
nar3

array([  2,  12,  30,  56,  90, 132])

In [14]:
# Aggregation function
np.sum(nums)

42

In [15]:
np.mean(nums)

7.0

In [16]:
np.max(nums)

12

In [17]:
np.size(nums)

6

In [18]:
np.min(nums)

2

### Numpy boolean indexing

In [24]:
x = np.array(nums)
x
x < 2

array([False, False, False, False, False, False])

In [25]:
x > 3

array([False,  True,  True,  True,  True,  True])

In [26]:
y = np.array(num)
y

array([ 1,  3,  5,  7,  9, 11])

In [35]:
# using & which means 'and' and | which means 'or'

z = x[(x <4) & (x >3)]
z

array([], dtype=int32)

In [31]:
z1 = x[(x <2) | (x >3)]
z1

array([ 4,  6,  8, 10, 12])

In [38]:
x.shape

(6,)

### Numpy algebra operations

In [4]:
list1 = [1, 3, 6, 4, 9, 7]

In [68]:
x1 = np.array([1,2,3,4])
x1

array([1, 2, 3, 4])

In [69]:
x2 = np.array([5,6,7,8])
x2

array([5, 6, 7, 8])

In [75]:
x3 = np.dot(x1, x2)
print(x3)

70


In [80]:
np.size(x1)

4

In [90]:
np.resize(x1, (3, 4))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [97]:
np.shape(x1)

(4,)

In [9]:
list2 = [2, 4, 6, 8, 10, 12]
np.array(list2)

array([ 2,  4,  6,  8, 10, 12])

In [107]:
np.array(list2).reshape(2,3)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### Pandas Series

In [13]:
#import pandas library
import pandas as pd
#create a pandas Series
class_scores = pd.Series({'jeol':60,
                          'jane':80,
                          'chizzy':100,
                          'nicole':95,
                          'amy': 98,
                          'josh':75},
                         name = 'class_scores')
class_scores

jeol       60
jane       80
chizzy    100
nicole     95
amy        98
josh       75
Name: class_scores, dtype: int64

In [17]:
class_scores[class_scores>70]

jane       80
chizzy    100
nicole     95
amy        98
josh       75
Name: class_scores, dtype: int64

In [20]:
class_scores[2: 5]

chizzy    100
nicole     95
amy        98
Name: class_scores, dtype: int64

In [30]:
x = (20,10, 15, 40, 12, 30)

class_scores.add(x)

jeol       80
jane       90
chizzy    115
nicole    135
amy       110
josh      105
Name: class_scores, dtype: int64

In [23]:
class_scores/x

jeol      3.000000
jane      8.000000
chizzy    6.666667
nicole    2.375000
amy       8.166667
josh      2.500000
Name: class_scores, dtype: float64

### Pandas DataFrame

In [36]:
new_scores = pd.Series({'joel':10,
               'jane': 12,
               'chizzy':45,
               'nicole':15,
               'amy':20,
               'josh': 8},
              name = 'new_scores')
new_scores

joel      10
jane      12
chizzy    45
nicole    15
amy       20
josh       8
Name: new_scores, dtype: int64

In [43]:
pd.DataFrame({class_scores.name:class_scores, new_scores.name:new_scores})

class_scores  new_scores
amy             98.0        20.0
chizzy         100.0        45.0
jane            80.0        12.0
jeol            60.0         NaN
joel             NaN        10.0
josh            75.0         8.0
nicole          95.0        15.0

In [40]:
# selecting the first column

pd.DataFrame(new_scores[0:])

new_scores
joel            10
jane            12
chizzy          45
nicole          15
amy             20
josh             8

In [41]:
pd.DataFrame(class_scores[:4])

class_scores
jeol              60
jane              80
chizzy           100
nicole            95

In [47]:
# selecting the first two rows and all the columns

x = pd.DataFrame({class_scores.name:class_scores, new_scores.name:new_scores})

pd.DataFrame(x[:2])

class_scores  new_scores
amy             98.0        20.0
chizzy         100.0        45.0

### Indexing in pandas using iloc and loc

In [53]:
# iloc is used for slicing integers while loc is used to slice labels
# selecting the first two rows and two columns
x.iloc[:2,:2]

class_scores  new_scores
amy             98.0        20.0
chizzy         100.0        45.0

In [61]:
#selecting the all columns and the 6th row

x.loc['josh', :]

class_scores    75.0
new_scores       8.0
Name: josh, dtype: float64

In [62]:
# selecting the second row and column

x.iloc[2:3, 1:]

new_scores
jane        12.0